# Generated by Django 5.0.6 on 2024-06-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_locationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationData',
        ),
    ]
