# Generated by Django 5.0.6 on 2024-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_delete_locationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
