# Generated by Django 5.0.6 on 2024-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_locationdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='locationdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='search',
            name='address',
        ),
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
        migrations.AddField(
            model_name='locationdata',
            name='application_id',
            field=models.CharField(default='DEFAULT_ID', max_length=100),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='area_type',
            field=models.CharField(default='Urban', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationdata',
            name='loan_account_number',
            field=models.CharField(default='Urban', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationdata',
            name='product',
            field=models.CharField(default='Urban', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationdata',
            name='state',
            field=models.CharField(default='Urban', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='pincode',
            field=models.CharField(default='Urban', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
